"""
This module exposes languages catalogs.

:copyright: (c) 2026 by Albaintor
:license: Mozilla Public License Version 2.0, see LICENSE for more details.
"""

LANGUAGES_KEYS = {
    "und_UND": "und",
    "mul_MUL": "mul",
    "zxx_ZXX": "zxx",
    "en_US": "en",
    "en_GB": "en",
    "fr_FR": "fr",
    "fr_CA": "fr",
    "fr_BE": "fr",
    "fr_CH": "fr",
    "es_ES": "es",
    "es_MX": "es",
    "es_AR": "es",
    "de_DE": "de",
    "de_AT": "de",
    "de_CH": "de",
    "nl_NL": "nl",
    "nl_BE": "nl",
    "it_IT": "it",
    "pt_PT": "pt",
    "pt_BR": "pt",
    "ru_RU": "ru",
    "pl_PL": "pl",
    "cs_CZ": "cs",
    "sk_SK": "sk",
    "hu_HU": "hu",
    "ro_RO": "ro",
    "bg_BG": "bg",
    "sr_RS": "sr",
    "hr_HR": "hr",
    "sl_SI": "sl",
    "sv_SE": "sv",
    "no_NO": "no",
    "da_DK": "da",
    "fi_FI": "fi",
    "is_IS": "is",
    "el_GR": "el",
    "tr_TR": "tr",
    "ar_SA": "ar",
    "he_IL": "he",
    "fa_IR": "fa",
    "hi_IN": "hi",
    "th_TH": "th",
    "vi_VN": "vi",
    "ja_JP": "ja",
    "ko_KR": "ko",
    "zh_CN": "zh",
    "zh_TW": "zh",
    "zh_HK": "zh",
    "id_ID": "id",
    "ms_MY": "ms",
    "tl_PH": "tl",
    "la_LA": "la",
}

LANGUAGES = {
    "dis": {
        "en": "Disabled",
        "fr": "Désactivé",
        "es": "Desactivado",
        "de": "Deaktiviert",
        "zh": "已禁用",
        "ja": "無効",
        "nl": "Uitgeschakeld",
    },
    "und": {
        "en": "Undetermined",
        "fr": "indéterminé",
        "es": "indeterminado",
        "de": "unbestimmt",
        "zh": "未确定",
        "ja": "不明",
        "nl": "onbepaald",
    },
    "mul": {
        "en": "Multiple languages",
        "fr": "plusieurs langues",
        "es": "varios idiomas",
        "de": "mehrere Sprachen",
        "zh": "多种语言",
        "ja": "複数言語",
        "nl": "meerdere talen",
    },
    "zxx": {
        "en": "No linguistic content",
        "fr": "pas de contenu linguistique",
        "es": "sin contenido lingüístico",
        "de": "kein sprachlicher Inhalt",
        "zh": "无语言内容",
        "ja": "言語内容なし",
        "nl": "geen taalkundige inhoud",
    },
    "eng": {
        "en": "English",
        "fr": "anglais",
        "es": "inglés",
        "de": "Englisch",
        "zh": "英语",
        "ja": "英語",
        "nl": "Engels",
    },
    "fre": {
        "en": "French",
        "fr": "français",
        "es": "francés",
        "de": "Französisch",
        "zh": "法语",
        "ja": "フランス語",
        "nl": "Frans",
    },
    "fra": {
        "en": "French",
        "fr": "français",
        "es": "francés",
        "de": "Französisch",
        "zh": "法语",
        "ja": "フランス語",
        "nl": "Frans",
    },
    "spa": {
        "en": "Spanish",
        "fr": "espagnol",
        "es": "español",
        "de": "Spanisch",
        "zh": "西班牙语",
        "ja": "スペイン語",
        "nl": "Spaans",
    },
    "ger": {
        "en": "German",
        "fr": "allemand",
        "es": "alemán",
        "de": "Deutsch",
        "zh": "德语",
        "ja": "ドイツ語",
        "nl": "Duits",
    },
    "deu": {
        "en": "German",
        "fr": "allemand",
        "es": "alemán",
        "de": "Deutsch",
        "zh": "德语",
        "ja": "ドイツ語",
        "nl": "Duits",
    },
    "dut": {
        "en": "Dutch",
        "fr": "néerlandais",
        "es": "neerlandés",
        "de": "Niederländisch",
        "zh": "荷兰语",
        "ja": "オランダ語",
        "nl": "Nederlands",
    },
    "nld": {
        "en": "Dutch",
        "fr": "néerlandais",
        "es": "neerlandés",
        "de": "Niederländisch",
        "zh": "荷兰语",
        "ja": "オランダ語",
        "nl": "Nederlands",
    },
    "ita": {
        "en": "Italian",
        "fr": "italien",
        "es": "italiano",
        "de": "Italienisch",
        "zh": "意大利语",
        "ja": "イタリア語",
        "nl": "Italiaans",
    },
    "por": {
        "en": "Portuguese",
        "fr": "portugais",
        "es": "portugués",
        "de": "Portugiesisch",
        "zh": "葡萄牙语",
        "ja": "ポルトガル語",
        "nl": "Portugees",
    },
    "rus": {
        "en": "Russian",
        "fr": "russe",
        "es": "ruso",
        "de": "Russisch",
        "zh": "俄语",
        "ja": "ロシア語",
        "nl": "Russisch",
    },
    "ukr": {
        "en": "Ukrainian",
        "fr": "ukrainien",
        "es": "ucraniano",
        "de": "Ukrainisch",
        "zh": "乌克兰语",
        "ja": "ウクライナ語",
        "nl": "Oekraïens",
    },
    "pol": {
        "en": "Polish",
        "fr": "polonais",
        "es": "polaco",
        "de": "Polnisch",
        "zh": "波兰语",
        "ja": "ポーランド語",
        "nl": "Pools",
    },
    "ces": {
        "en": "Czech",
        "fr": "tchèque",
        "es": "checo",
        "de": "Tschechisch",
        "zh": "捷克语",
        "ja": "チェコ語",
        "nl": "Tsjechisch",
    },
    "cze": {
        "en": "Czech",
        "fr": "tchèque",
        "es": "checo",
        "de": "Tschechisch",
        "zh": "捷克语",
        "ja": "チェコ語",
        "nl": "Tsjechisch",
    },
    "slk": {
        "en": "Slovak",
        "fr": "slovaque",
        "es": "eslovaco",
        "de": "Slowakisch",
        "zh": "斯洛伐克语",
        "ja": "スロバキア語",
        "nl": "Slowaaks",
    },
    "slo": {
        "en": "Slovak",
        "fr": "slovaque",
        "es": "eslovaco",
        "de": "Slowakisch",
        "zh": "斯洛伐克语",
        "ja": "スロバキア語",
        "nl": "Slowaaks",
    },
    "hun": {
        "en": "Hungarian",
        "fr": "hongrois",
        "es": "húngaro",
        "de": "Ungarisch",
        "zh": "匈牙利语",
        "ja": "ハンガリー語",
        "nl": "Hongaars",
    },
    "ron": {
        "en": "Romanian",
        "fr": "roumain",
        "es": "rumano",
        "de": "Rumänisch",
        "zh": "罗马尼亚语",
        "ja": "ルーマニア語",
        "nl": "Roemeens",
    },
    "rum": {
        "en": "Romanian",
        "fr": "roumain",
        "es": "rumano",
        "de": "Rumänisch",
        "zh": "罗马尼亚语",
        "ja": "ルーマニア語",
        "nl": "Roemeens",
    },
    "bul": {
        "en": "Bulgarian",
        "fr": "bulgare",
        "es": "búlgaro",
        "de": "Bulgarisch",
        "zh": "保加利亚语",
        "ja": "ブルガリア語",
        "nl": "Bulgaars",
    },
    "srp": {
        "en": "Serbian",
        "fr": "serbe",
        "es": "serbio",
        "de": "Serbisch",
        "zh": "塞尔维亚语",
        "ja": "セルビア語",
        "nl": "Servisch",
    },
    "hrv": {
        "en": "Croatian",
        "fr": "croate",
        "es": "croata",
        "de": "Kroatisch",
        "zh": "克罗地亚语",
        "ja": "クロアチア語",
        "nl": "Kroatisch",
    },
    "slv": {
        "en": "Slovenian",
        "fr": "slovène",
        "es": "esloveno",
        "de": "Slowenisch",
        "zh": "斯洛文尼亚语",
        "ja": "スロベニア語",
        "nl": "Sloveens",
    },
    "swe": {
        "en": "Swedish",
        "fr": "suédois",
        "es": "sueco",
        "de": "Schwedisch",
        "zh": "瑞典语",
        "ja": "スウェーデン語",
        "nl": "Zweeds",
    },
    "nor": {
        "en": "Norwegian",
        "fr": "norvégien",
        "es": "noruego",
        "de": "Norwegisch",
        "zh": "挪威语",
        "ja": "ノルウェー語",
        "nl": "Noors",
    },
    "dan": {
        "en": "Danish",
        "fr": "danois",
        "es": "danés",
        "de": "Dänisch",
        "zh": "丹麦语",
        "ja": "デンマーク語",
        "nl": "Deens",
    },
    "fin": {
        "en": "Finnish",
        "fr": "finnois",
        "es": "finés",
        "de": "Finnisch",
        "zh": "芬兰语",
        "ja": "フィンランド語",
        "nl": "Fins",
    },
    "isl": {
        "en": "Icelandic",
        "fr": "islandais",
        "es": "islandés",
        "de": "Isländisch",
        "zh": "冰岛语",
        "ja": "アイスランド語",
        "nl": "IJslands",
    },
    "ice": {
        "en": "Icelandic",
        "fr": "islandais",
        "es": "islandés",
        "de": "Isländisch",
        "zh": "冰岛语",
        "ja": "アイスランド語",
        "nl": "IJslands",
    },
    "ell": {
        "en": "Greek",
        "fr": "grec",
        "es": "griego",
        "de": "Griechisch",
        "zh": "希腊语",
        "ja": "ギリシャ語",
        "nl": "Grieks",
    },
    "gre": {
        "en": "Greek",
        "fr": "grec",
        "es": "griego",
        "de": "Griechisch",
        "zh": "希腊语",
        "ja": "ギリシャ語",
        "nl": "Grieks",
    },
    "tur": {
        "en": "Turkish",
        "fr": "turc",
        "es": "turco",
        "de": "Türkisch",
        "zh": "土耳其语",
        "ja": "トルコ語",
        "nl": "Turks",
    },
    "ara": {
        "en": "Arabic",
        "fr": "arabe",
        "es": "árabe",
        "de": "Arabisch",
        "zh": "阿拉伯语",
        "ja": "アラビア語",
        "nl": "Arabisch",
    },
    "heb": {
        "en": "Hebrew",
        "fr": "hébreu",
        "es": "hebreo",
        "de": "Hebräisch",
        "zh": "希伯来语",
        "ja": "ヘブライ語",
        "nl": "Hebreeuws",
    },
    "per": {
        "en": "Persian",
        "fr": "persan",
        "es": "persa",
        "de": "Persisch",
        "zh": "波斯语",
        "ja": "ペルシャ語",
        "nl": "Perzisch",
    },
    "fas": {
        "en": "Persian",
        "fr": "persan",
        "es": "persa",
        "de": "Persisch",
        "zh": "波斯语",
        "ja": "ペルシャ語",
        "nl": "Perzisch",
    },
    "hin": {
        "en": "Hindi",
        "fr": "hindi",
        "es": "hindi",
        "de": "Hindi",
        "zh": "印地语",
        "ja": "ヒンディー語",
        "nl": "Hindi",
    },
    "tha": {
        "en": "Thai",
        "fr": "thaï",
        "es": "tailandés",
        "de": "Thailändisch",
        "zh": "泰语",
        "ja": "タイ語",
        "nl": "Thais",
    },
    "vie": {
        "en": "Vietnamese",
        "fr": "vietnamien",
        "es": "vietnamita",
        "de": "Vietnamesisch",
        "zh": "越南语",
        "ja": "ベトナム語",
        "nl": "Vietnamees",
    },
    "jpn": {
        "en": "Japanese",
        "fr": "japonais",
        "es": "japonés",
        "de": "Japanisch",
        "zh": "日语",
        "ja": "日本語",
        "nl": "Japans",
    },
    "kor": {
        "en": "Korean",
        "fr": "coréen",
        "es": "coreano",
        "de": "Koreanisch",
        "zh": "韩语",
        "ja": "韓国語",
        "nl": "Koreaans",
    },
    "chi": {
        "en": "Chinese",
        "fr": "chinois",
        "es": "chino",
        "de": "Chinesisch",
        "zh": "中文",
        "ja": "中国語",
        "nl": "Chinees",
    },
    "zho": {
        "en": "Chinese",
        "fr": "chinois",
        "es": "chino",
        "de": "Chinesisch",
        "zh": "中文",
        "ja": "中国語",
        "nl": "Chinees",
    },
    "yue": {
        "en": "Cantonese",
        "fr": "cantonais",
        "es": "cantonés",
        "de": "Kantonesisch",
        "zh": "粤语",
        "ja": "広東語",
        "nl": "Kantonees",
    },
    "ind": {
        "en": "Indonesian",
        "fr": "indonésien",
        "es": "indonesio",
        "de": "Indonesisch",
        "zh": "印度尼西亚语",
        "ja": "インドネシア語",
        "nl": "Indonesisch",
    },
    "msa": {
        "en": "Malay",
        "fr": "malais",
        "es": "malayo",
        "de": "Malaiisch",
        "zh": "马来语",
        "ja": "マレー語",
        "nl": "Maleis",
    },
    "may": {
        "en": "Malay",
        "fr": "malais",
        "es": "malayo",
        "de": "Malaiisch",
        "zh": "马来语",
        "ja": "マレー語",
        "nl": "Maleis",
    },
    "tgl": {
        "en": "Tagalog",
        "fr": "tagalog",
        "es": "tagalo",
        "de": "Tagalog",
        "zh": "他加禄语",
        "ja": "タガログ語",
        "nl": "Tagalog",
    },
    "lat": {
        "en": "Latin",
        "fr": "latin",
        "es": "latín",
        "de": "Latein",
        "zh": "拉丁语",
        "ja": "ラテン語",
        "nl": "Latijn",
    },
}
